billingrepo/dataentry/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url
from django.views.generic import TemplateView

from . import views


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/dataentry_home.html'),
        name="home"),
    # URL pattern for the PatientListView
    url(
        regex=r'^patients/$',
        view=views.PatientListView.as_view(),
        name='patient_list'
    ),

    # URL pattern for a new patient
    url(
        regex=r'^patients/new/$',
        view=views.NewPatient,
        name='patient_new'
    ),

    # URL pattern for the PatientRedirectView
    url(
        regex=r'^patients/~redirect/$',
        view=views.PatientRedirectView.as_view(),
        name='patient_redirect'
    ),

    # URL pattern for the PatientDetailView
    url(
        regex=r'^patients/(?P<pid>[\w.@+-]+)/$',
        view=views.PatientDetailView.as_view(),
        name='patient_detail'
    ),

    # URL pattern for the PatientUpdateView
    url(
        regex=r'^patients/update/(?P<pid>[\w.@+-]+)/$',
        view=views.PatientUpdateView.as_view(),
        name="patient_update"),
    # sites
    url(regex=r'^sites/$',
        view=views.SiteListView.as_view(),
        name="site_list"),
    url(regex=r'^sites/new/$',
        view=views.site_entry,
        name="site_entry"),
    url(regex=r'^sites/~redirect/$',
        view=views.SiteRedirectView.as_view(),
        name="site_redirect"),
    url(regex=r'^sites/(?P<id>[\w.@+-]+)/$',
        view=views.SiteDetailView.as_view(),
        name="site_detail"),
    url(regex=r'^sites/update/(?P<id>[\w.@+-]+)$',
        view=views.SiteUpdateView.as_view(),
        name="site_update"),
]

billingrepo/setup/urls.py
from django.conf.urls import url

from django.views.generic import TemplateView
from . import views


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/setup_home.html'),
        name="home"),
    url(r'^icd/', views.icd_entry, name="icd_entry"),

    url(r'upload/$', views.upload_file, name="file_upload"),

]

billingrepo/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name="home"),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include("billingrepo.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^dataentry/', include('billingrepo.dataentry.urls', namespace="dataentry")),
    url(r'^setup/', include('billingrepo.setup.urls', namespace="setup")),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception("Bad Request!")}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception("Permission Denied")}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception("Page not Found")}),
        url(r'^500/$', default_views.server_error),
    ]

billingrepo/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_("Name of User"), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

billingrepo/dataentry/forms.py
from django import forms

from .models import Patient, Site, Order, Contact, Client, Claim, ClientContact


class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        exclude = ['pid', ]


class SiteForm(forms.ModelForm):
    class Meta:
        model = Site
        exclude = ['id', ]


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ['order_id', ]


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        exclude = ['id', ]


class ClaimForm(forms.ModelForm):
    class Meta:
        model = Claim
        exclude = ['claim_id', ]


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        exclude = ['id', ]


class ClientContactForm(forms.ModelForm):
    class Meta:
        model = ClientContact
        exclude = ['id', ]

billingrepo/setup/forms.py
from django import forms

from .models import ICD, CPT, Test, Panel, Payor, PriceSheet


class ICDForm(forms.ModelForm):
    class Meta:
        model = ICD
        fields = ['code', 'description', 'version', 'status', 'end_date']


class CPTForm(forms.ModelForm):
    class Meta:
        model = CPT
        fields = ['code', 'description', 'version', 'status', 'end_date']


class TestForm(forms.ModelForm):
    class Meta:
        model = Test
        exclude = []


class PanelForm(forms.ModelForm):
    class Meta:
        model = Panel
        exclude = ['id', ]


class PayorForm(forms.ModelForm):
    class Meta:
        model = Panel
        exclude = ['id']


class PriceSheetForm(forms.ModelForm):
    class Meta:
        model = PriceSheet
        exclude = []


class UploadForm(forms.Form):
    type = forms.ChoiceField(required=True,
           choices=(('ICD', 'ICD'), ('Payors', 'Payors'), ('Tests', 'Tests'),
                    ('CPT', 'CPT'), ('Panels', 'Panels'), ))
    file = forms.FileField(required=True, label="Select File to upload")

billingrepo/dataentry/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.db.models import Q
from django.shortcuts import render
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from braces.views import LoginRequiredMixin

from .models import Patient, Site
from .forms import PatientForm, SiteForm


nav = "dataentry"
sidebar_items = [
        {"name": "patients",
         "url": "dataentry:patient_list"},
        {"name": "sites",
         "url": "dataentry:site_list"},
]


# Create your views here.
class SiteDetailView(DetailView):
    model = Site
    slug_field = "id"
    slug_url_kwarg = "id"

    def get_context_data(self, **kwargs):
        context = super(SiteDetailView, self).get_context_data(**kwargs)
        context['nav'] = nav
        context['side'] = "sites"
        context['sidebar_items'] = sidebar_items
        return context


class SiteRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("dataentry:site_detail",
                       kwargs={"id": self.request.site.id})


class SiteUpdateView(LoginRequiredMixin, UpdateView):
    model = Site
    fields = ['name', 'address1', 'address2', 'city', 'state', 'zip_code',
              'phone_no', 'fax_no', 'status', ]
    slug_field = "id"
    slug_url_kwarg = "id"

    def get_context_data(self, **kwargs):
        context = super(SiteUpdateView, self).get_context_data(**kwargs)
        context['nav'] = nav
        context['side'] = "sites"
        context['sidebar_items'] = sidebar_items
        return context


class SiteListView(LoginRequiredMixin, ListView):
    model = Site
    list_display = ('last_name', 'first_name', 'birth_date', 'age', 'status', )
    search_fields = ('last_name', 'first_name', 'birth_date', )

    def get_object(self, queryset=None):
        obj = self.objects.get(id=self.kwargs['id'])
        return obj

    def get_context_data(self, **kwargs):
        context = super(SiteListView, self).get_context_data(**kwargs)
        context['nav'] = nav
        context['side'] = "sites"
        context['sidebar_items'] = sidebar_items
        return context


def site_entry(request):
    title = "Site Data Entry"
    if request.user.is_authenticated():
        usrnam = request.user
    else:
        usrnam = "N/A"
    form = SiteForm(request.POST or None)

    context = {
        "title": title,
        "msg": "Logged in as: %s" % usrnam,
        "nav": nav,
        "side": "sites",
        "sidebar_items": sidebar_items,
        "form": form,
    }

    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        context = {
            "msg": "Saved",
        }
    return render(request, 'forms.html', context)


class PatientDetailView(LoginRequiredMixin, DetailView):
    model = Patient
    slug_field = "pid"
    slug_url_kwarg = "pid"

    def get_context_data(self, **kwargs):
        context = super(PatientDetailView, self).get_context_data(**kwargs)
        context['nav'] = nav
        context['side'] = "patients"
        context['sidebar_items'] = sidebar_items
        return context


class PatientRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("dataentry:detail",
                       kwargs={"pid": self.request.patient.pid})


class PatientUpdateView(LoginRequiredMixin, UpdateView):

    model = Patient
    slug_field = "pid"
    slug_url_kwarg = "pid"
    fields = ['external_pid', 'ssn', 'first_name', 'last_name', 'mi',
              'birth_date', 'sex', 'address1', 'address2', 'city', 'state',
              'zip_code', 'phone_no', 'status', ]

    def get_context_data(self, **kwargs):
        context = super(PatientUpdateView, self).get_context_data(**kwargs)
        context['nav'] = nav
        context['side'] = "patients"
        context['sidebar_items'] = sidebar_items
        return context


class PatientListView(LoginRequiredMixin, ListView):
    model = Patient
    is_paginated = True
    paginate_by = 20
    queryset = Patient.objects.all()

    def get_context_data(self, **kwargs):
        context = super(PatientListView, self).get_context_data(**kwargs)
        context['nav'] = nav
        context['side'] = "patients"
        context['sidebar_items'] = sidebar_items
        return context

    def get_queryset(self):
        qs = super(PatientListView, self).get_queryset()

        query = self.request.GET.get("q")
        if query:
            qs = self.model.objects.filter(
                Q(last_name__icontains=query) |
                Q(first_name__icontains=query)
            )
        return qs


def NewPatient(request):
    title = "Patient Data Entry"
    if request.user.is_authenticated():
        usrnam = request.user
    else:
        usrnam = "N/A"
    form = PatientForm(request.POST or None)

    context = {
        "title": title,
        "msg": "Logged in as: %s" % usrnam,
        "nav": nav,
        "side": 'patients',
        "sidebar_items": sidebar_items,
        "form": form,
    }

    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        context = {
            "msg": "Saved",
        }
    return render(request, 'dataentry/forms.html', context)

billingrepo/setup/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from .forms import ICDForm, UploadForm, CPTForm, PayorForm, TestForm, PanelForm, PriceSheetForm
from .functions import handle_uploaded_file
from .models import ICD

# Create your views here.
nav = "setup"
sidebar_items = [
        {"name": "icd",
         "url": "setup:home"},
        ]


def setup_home(request):
    context = {
            'nav': nav,
    }
    return render(request, 'setup_home.html', context)


class ICDListView(ListView):
    model = ICD
    list_display = ('__str__', 'is_expired')


def icd_entry(request):
    msg = "Add manually or upload file"
    form = ICDForm(request.POST or None)

    context = {
            "title": "ICD Codes",
            "msg": msg,
            "nav": nav,
            'side': 'icd',
            "sidebar_items": sidebar_items,
            "form": form
    }
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        msg = "Saved"
        context = {
            "msg": msg,
    }
    return render(request, 'forms.html', context)

def upload_file(request):
    msg = "Manually upload file"
    form = UploadForm(request.POST or None)

    context = {
            "title": "File Uploads",
            "msg": msg,
            "nav": nav,
            'side': 'upload',
            "sidebar_items": sidebar_items,
            "form": form
    }
    if request.method == 'POST':
        form = UploadForm(request.POST, request.FILES)
        if form.is_valid():
            model = form.cleaned_data.get("type")
            handle_uploaded_file(request.FILES['file'], model)
            context["msg"] = "Uploaded"
            context["form"] = UploadForm()
            return render(request, 'upload.html', context)
    else:

        form = UploadForm()
        return render(request, 'pages/upload.html', context)

billingrepo/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

billingrepo/templates/dataentry/forms.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="row">
  <div class="col-sm-9 col-sm-offset-3">

  {% if title %}
    <h1 class="title">{{ title }}</h1>
    <h2 class="subtitle">{{ msg }} </h2>
  {% endif %}

    <form method = 'POST' action = ''>{% csrf_token %}

      {{ form|crispy }}

      <input class='btn btn-primary' type='submit' value='Submit' />

    </form>
  </div>
</div>
{% endblock %}

billingrepo/templates/dataentry/patient_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}patient: {{ object.pid }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.pid }} ({{ object.status }})</h2>
      {% if object.last_name %}
      <p>{{ object.last_name }}, {{ object.first_name }} {{ object.mi }} - Age: {{ object.age }}</p>
      <p>{{ object.address1 }}<br>
      {{ object.address2 }}<br>
      {{ object.city }}, {{ object.state }} {{ object.zip_code }}</p>
      {% endif %}
    </div>
  </div>

{% if object %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12 ">
    <a class="btn btn-primary" href="{% url 'dataentry:patient_update' patient.pid %}">Update</a>
    <a class="btn btn-primary" href="{% url 'dataentry:patient_list' %}">Done</a>
    <!-- Your Stuff: Custom patient template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

billingrepo/templates/dataentry/patient_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ patient.pid }}{% endblock %}

{% block content %}
<h1>{{ patient.pid }}</h1>
<form class="form-horizontal" method="post" action="{% url 'dataentry:patient_update' patient.pid %}">
  {% csrf_token %}
  {{ form|crispy }}
  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn">Update</button>
      <a class="btn btn-warning" href="{% url 'dataentry:patient_list' %}">Cancel</a>
    </div>
  </div>
</form>
{% endblock %}

billingrepo/templates/dataentry/patient_list.html
{% extends "base.html" %}
{% load static %}{% load i18n %}
{% block title %}Members{% endblock %}

{% block content %}

<div class="container">

  <h2>Patients</h2>

  <div class="nav navbar right">
    <a class="btn-primary" href="new">Add New</a>
    <form action="{% url 'dataentry:patient_list' %}"  method="GET" accept-charset="utf-8">
      <button class="default" type="submit"></button>
      <input class="searchfield" id="searchbox" name="q" type="text" value={{ request.GET.q }}placeholder="Search">
    </form>
  </div>
  <div class="list-group">
    {% for patient in patient_list %}
    <a href="{% url 'dataentry:patient_detail' patient.pid %}" class="list-group-item">
      {{ patient.pid }} - <b>{{ patient.last_name }}, {{ patient.first_name }}</b>
      - Age: {{ patient.age}}
    </a>
    {% endfor %}

  </div>
</div>

{% endblock content %}

billingrepo/templates/dataentry/site_detail.html
{% extends "base.html" %}
{% load static %}{% load i18n %}{% load crispy_forms_tags $}

{% block title %}Site: {{ object.id }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.id }} ({{ object.status }})</h2>
      {% if object.name %}
      <p>{{ object.name }}</p>
      <p>{{ object.address1 }}<br>
      {{ object.address2 }}<br>
      {{ object.city }}, {{ object.state }} {{ object.zip_code }}</p>
      {% endif %}
    </div>
  </div>

  {% if object %}
  <!-- Action buttons -->
  <div class="row">

    <div class="col-sm-12 ">
      <a class="btn btn-primary" href="{% url 'dataentry:site_update' site.id %}">Update</a>
      <a class="btn btn-primary" href="{% url 'dataentry:site_list' %}">Done</a>
      <!-- Your Stuff: Custom site template urls -->
    </div>

  </div>
  <!-- End Action buttons -->
  {% endif %}


</div>
{% endblock content %}

billingrepo/templates/dataentry/site_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ site.id }}{% endblock %}

{% block content %}
<div class="row">
  <div class="col-sm-9 col-sm-offset-3">
    <h1 class="subtitle">Update site</h1>
    <h2>{{ site.name }}</h2>
    <form class="form-horizontal" method="post" action="{% url 'dataentry:site_update' site.id %}">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="control-group">
          <div class="controls">
            <button type="submit" class="btn">Update</button>
          </div>
        </div>
    </form>
  </div>
</div>
{% endblock %}

billingrepo/templates/dataentry/site_list.html
{% extends "base.html" %}
{% load static %}{% load i18n %}{% load crispy_forms_tags $}

{% block content %}

<div class="row">
  <div class="col-sm-9 col-sm-offset-3">

    <h1>Sites</h1>

    <div class="nav navbar right">
      <a class="btn-primary" href="new">Add New</a>
    </div>
    <div class="table table-striped table-hover">
      {% for site in site_list %}
      <tr>
        <a type="button" class="btn btn-default btn-lg btn-block" href="{% url 'dataentry:site_detail' site.id %}">
          {{ site.id }} - <b>{{ site.name }}, {{ site.status }}</b>
        </a>
      </tr>
      {% endfor %}

    </div>
  </div>
</div>

{% endblock content %}